#!/usr/bin/env python3

import argparse
import subprocess
import re

COMMENT_CHAR = ['#', '//', '\*', '%']

def parse_args():
    parser = argparse.ArgumentParser(description='TODO')
    parser.add_argument('path', type=str)
    return vars(parser.parse_args())

if __name__ == '__main__':
    args = parse_args()
    regex = '|'.join(['^\W*' + c + '\W*TODO.*$' for c in COMMENT_CHAR])
    result = subprocess.run(
        ['grep', '-ronPI', regex, args['path']], stdout=subprocess.PIPE)
    result = result.stdout.decode('ascii').splitlines()
    for line in result:
        file, line, message = re.search('([^:]*):([^:]):(.*)', line).groups()
        print("{:20s} {:05d}     {:s}".format(file, int(line), message))
